models:
  translation:
    container_name: "models"
    blob_prefix: "translation/"
    model_type: "seq2seq"

  transcription:
    container_name: "models"
    blob_prefix: "transcription/"
    model_type: "asr"

  tts:
    container_name: "models"
    blob_prefix: "text-to-speech/"
    model_type: "text-to-speech"
